version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "org.junit.*"
      - dependency-name: "org.mockito.*"